class Bombsubject
{
    - observersFlying:List<AbstractFlyingObject>
    +registerObserver(AbstractFlyingObject object): void
    +removeObserver(AbstractFlyingObject object): void
    +notifyObservers(): void
}

class AbstractFlyingObject
{
    +update(): void
}

class BaseBullet
{
    +update(): void
}

class AbstractAircraft
{
    +update(): void
}

AbstractFlyingObject <|-- BaseBullet
AbstractFlyingObject <|-- AbstractAircraft